-- Create the messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  datetime timestamptz not null,
  date text,
  time text,
  sender text,
  type text,
  text text,
  isnew boolean default false,
  created_at timestamptz default now()
);

-- Enable Row Level Security (RLS)
alter table public.messages enable row level security;

-- Create a policy to allow anyone to read messages (since it's a chat app)
-- Adjust this if you have authentication!
create policy "Allow public read access"
on public.messages for select
using (true);

-- Create a policy to allow anyone to insert messages
create policy "Allow public insert access"
on public.messages for insert
with check (true);

-- Create a realtime publication for the messages table
alter publication supabase_realtime add table public.messages;
